title: Kbot Infrastructure Template
description: Provisions Kbot infrastructure in existing VCN
informationalText: "The Resource Manager Stack just creates the infrastructure components (LLM VMs, OpenSearch Cluster, APEX ADB, OS bucket, Bastion Service)."
schemaVersion: 1.1.0
version: "20200822"
locale: "en"

variableGroups:
  - title: "Existing VCN"
    visible: true
    variables:
      - network_compartment_ocid
      - vcn_ocid
      - subnet_ocid
  
  - title: "IAM Configuration"
    visible: true
    variables:
      - iam_compartment_ocid
  
  - title: "Kbot Configuration"
    visible: true
    variables:
      - compartment_ocid
  
  - title: "VMs Configuration"
    visible: true
    variables:
      - ssh_public_key
  
  - title: APEX ADB Configuration
    required: true
    visible: true
    variables:
      - adb_admin_password
      - adb_display_name
      - adb_email_ids

  - title: "OpenSearch Cluster Configuration"
    visible: true
    required: true
    variables:
      - opensearch_cluster_display_name
      - security_master_user_name
      - security_master_user_password
      - opensearch_notification_email_ids

#  - title: "Tags"
 #   visible: true
  #  variables:
   #   - freeform_tags

variables:
  # Hidden variables
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    type: string
    required: true
    visible: false

  region:
    title: Region
    description: The region in which to create all resources
    type: oci:identity:region:name
    required: true
    visible: false

  user_ocid:
    title: User ID
    description: The Oracle Cloud Identifier (OCID) for the user
    type: string
    visible: false

  fingerprint:
    title: Private Key Fingerprint
    type: string
    visible: false

  private_key_path:
    title: Private Key Path
    type: string
    visible: false

  network_compartment_ocid:
    title: Virtual Cloud Network Compartment
    description: The target compartment to create network.
    type: oci:identity:compartment:id
    required: true
    visible: true
    default: compartment_ocid

  iam_compartment_ocid:
    title: IAM Compartment
    description: The target compartment to IAM policies.
    type: oci:identity:compartment:id
    required: true
    visible: true
    default: compartment_ocid

  vcn_ocid:
    title: Existing VCN
    description: The VCN
    type: oci:core:vcn:id
    required: true
    visible: true
    dependsOn:
      compartmentId: network_compartment_ocid

  #vcn_name:
  #  title: Virtual Cloud Network name
  #  visible: true
  #  type: string
    #default: SpokeD
  #  required: true

  subnet_ocid:
    title: Existing Subnet
    visible: true
    type: oci:core:subnet:id
    #default: 192.168.104.0/22
    required: true
    dependsOn:
      compartmentId: network_compartment_ocid
      vcnId: vcn_ocid
    filter:
      name: "Private Subnets Only"
      attribute: prohibitPublicIpOnVnic
      value: true 

  adb_admin_password:
    type: password
    title: "Autonomous DB Admin Password"
    description: "The password for the Autonomous Database ADMIN user. Must meet Oracle Cloud password complexity rules."
    required: true
    secret: true

  security_master_user_name:
    type: string
    title: "OpenSearch Master Username"
    description: "The username for the OpenSearch master user."
    required: true

  security_master_user_password:
    type: password
    title: "OpenSearch Master Password"
    description: "The password for the OpenSearch master user. Must meet OCI complexity rules."
    required: true
    secret: true

  adb_display_name:
    type: string
    title: "APEX ADB display name"
    description: "The ADB display name."
    required: true

  
  opensearch_cluster_display_name:
    type: string
    title: "OpenSearch Cluster display name"
    description: "The OpenSearch display name."
    required: true

  adb_email_ids:
    type: string
    title: "Notification e-mial adsress"
    description: "The ADB notification e-mail address."
    required: false
    

  opensearch_notification_email_ids:
    type: string
    title: "Notification e-mial adsress"
    description: "The OpenSearch notification e-mail address."
    required: false
   

  # General Configuration
 # remote_module:
  #  title: Remote Module
  #  description: Remote or local module 9ORM only supports locla)
  #  type: enum
   #   - "Local spoke module"
   #   - "Remote spoke module"
   # requierd: true
   # default: - "Remote spoke module"
  
  compartment_ocid:
    title: Target Compartment
    description: The target compartment to provision Kbot infrastructure.
    type: oci:identity:compartment:id
    required: true
    visible: true
    default: compartment_ocid

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH
    visible: true
#HIDE those

  ATP_database_db_version:
    type: string
    visible: false

  ATP_database_license_model:
    type: string
    visible: false

  ATP_is_data_guard_enabled:
    type: boolean
    visible: false

  ATP_private_endpoint_label:
    type: string
    visible: false

  adb_cpu_core_count:
    type: number
    visible: false

  adb_data_storage_size_in_tbs:
    type: number
    visible: false

  adb_db_name:
    type: string
    visible: false

  adb_db_workload:
    type: string
    visible: false

  adb_notification_email:
    type: string
    visible: false

  adb_is_auto_scaling_enabled:
    type: boolean
    visible: false

  adb_is_free_tier:
    type: boolean
    visible: false

  adb_public_access_type:
    type: string
    visible: false

  adb_storage_tier:
    type: string
    visible: false

  availability_domain_name:
    type: string
    visible: false

  bastion_client_cidr_block_allow_list:
    type: list(string)
    visible: false

  bastion_name:
    type: string
    visible: false

  instance_os:
    type: string
    visible: false

  linux_os_version:
    type: string
    visible: false

  llm_vm_count:
    type: number
    visible: false

  node_flex_shape_memory:
    type: number
    visible: false

  node_flex_shape_ocpus:
    type: number
    visible: false

  node_image_id:
    type: string
    visible: false

  node_shape:
    type: string
    visible: false

  opendashboard_node_host_shape:
    type: string
    visible: false

  opensearch_cluster_data_node_count:
    type: number
    visible: false
  opensearch_cluster_data_node_host_memory_gb:
    type: number
    visible: false

  opensearch_cluster_data_node_host_ocpu_count:
    type: number
    visible: false

  opensearch_cluster_data_node_host_type:
    type: string
    visible: false

  opensearch_cluster_data_node_storage_gb:
    type: number
    visible: false

  opensearch_cluster_master_node_count:
    type: number
    visible: false

  opensearch_cluster_master_node_host_memory_gb:
    type: number
    visible: false

  opensearch_cluster_master_node_host_ocpu_count:
    type: number
    visible: false

  opensearch_cluster_master_node_host_type:
    type: string
    visible: false

  opensearch_cluster_opendashboard_node_count:
    type: number
    visible: false

  opensearch_cluster_opendashboard_node_host_memory_gb:
    type: number
    visible: false

  opensearch_cluster_opendashboard_node_host_ocpu_count:
    type: number
    visible: false

  opensearch_cluster_software_version:
    type: string
    visible: false

  osb1_name:
    type: string
    visible: false

  osb1_public_access_type:
    type: string
    visible: false

  osb1_storage_tier:
    type: string
    visible: false

  release:
    type: string
    visible: false

  security_mode:
    type: string
    visible: false

  ssh_authorized_keys:
    type: string
    visible: false

  ssh_private_key_path:
    type: string
    visible: false
    secret: true
    
  vcn:
    type: string
    visible: false

  vcn_cidr:
    type: string
    visible: false

  vm_instance_name:
    type: string
    visible: false
  
  cus_image_name:
    type: string
    visible: false

  cus_image_url:
    type: string
    visible: false

 # db_admin_password:
  #  title: Database Admin User Password
   # description: "The password for the database. Password must be 9 to 30 characters and contain at least 2 uppercase, 2 lowercase, 2 special, and 2 numeric characters. The special characters must be _, #, or -. For example, XYh1z0#_d"
    #type: password
   # pattern: "^(?=.*[a-z].*[a-z])(?=.*[A-Z].*[A-Z])(?=.*\\d.*\\d)(?=.*[-_#].*[-_#])[a-zA-Z0-9\\S]{9,32}$"
   # required: true
   # visible: ebs_database_required
 
#  bastion_user:
#    title: Bastion user
#    description: bastion user
#    type: string
#    default: opc
#    visible: false

#  freeform_tags:
#    type: string
#    visible: true

#outputGroups:
#  - title: Outputs
#    outputs:
#      - BastionPublicIPs


outputs:
#  BastionPublicIPs:
#    title: "Bastion Host Details"
#    type: string
#    visible: true
  generated_ssh_private_key:
    title: "Private VM ssh key"
    type: string
    visible: true
  
  opensearch_api_endpoint:
    title: "Open Search API endpoint"
    type: string
    visible: true
  
  opensearch_dashboards_api_endpoint: 
    tittle: "Open Search API Dashboard endpoint"
    type: string
    visible: true